/**
 * 策略模板库
 * 提供各种类型的量化交易策略模板
 * 注意：MiniQMT支持已移除，仅保留Qlib专用模板
 */

import {
  StrategyTemplate,
  StrategyComponent,
  ComponentType,
  StrategyCategory,
  MarketType,
  Timeframe,
  RiskLevel,
  ValidationRule
} from '../types/strategy';

// ==================== 基础验证规则 ====================

const baseValidationRules: any[] = [
  {
    field: 'initialCapital',
    rule: 'required|min:10000',
    message: '初始资金至少需要10,000元'
  },
  {
    field: 'maxDrawdown',
    rule: 'max:50',
    message: '最大回撤不能超过50%'
  },
  {
    field: 'commissionRate',
    rule: 'max:0.005',
    message: '手续费率不能超过0.5%'
  }
];

const trendValidationRules: any[] = [
  ...baseValidationRules,
  {
    field: 'fastPeriod',
    rule: 'required|min:5|max:50',
    message: '快线周期必须在5-50之间'
  },
  {
    field: 'slowPeriod',
    rule: 'required|min:10|max:200',
    message: '慢线周期必须在10-200之间'
  }
];

const meanReversionValidationRules: any[] = [
  ...baseValidationRules,
  {
    field: 'lookbackPeriod',
    rule: 'required|min:10|max:100',
    message: '回看周期必须在10-100之间'
  },
  {
    field: 'entryThreshold',
    rule: 'required|min:1|max:5',
    message: '入场阈值必须在1-5之间'
  }
];

// ==================== 基础策略组件 ====================

const dataComponent: StrategyComponent = {
  type: 'DATA_HANDLING',
  name: 'MarketDataProcessor',
  description: '市场数据处理器',
  codeTemplate: '',
  requiredParams: [],
  validation: {
    requiredParams: [],
    validationRules: [],
    dependencies: []
  },
  required: true,
  parameters: {
    markets: ['CN'],
    dataSources: ['YahooFinance'],
    preprocessing: true
  }
};

const riskComponent: StrategyComponent = {
  type: 'RISK_CONTROL',
  name: 'BasicRiskManager',
  description: '基础风险管理器',
  codeTemplate: '',
  requiredParams: [],
  validation: {
    requiredParams: [],
    validationRules: [],
    dependencies: []
  },
  required: true,
  parameters: {
    stopLoss: 5,
    takeProfit: 15,
    maxDrawdown: 10,
    positionSize: 10
  }
};

const performanceComponent: StrategyComponent = {
  type: 'OPTIMIZATION',
  name: 'PerformanceAnalyzer',
  description: '性能分析器',
  codeTemplate: '',
  requiredParams: [],
  validation: {
    requiredParams: [],
    validationRules: [],
    dependencies: []
  },
  required: false,
  parameters: {
    enableMetrics: true,
    benchmark: 'CSI300'
  }
};

// ==================== 策略模板库 ====================

export const STRATEGY_TEMPLATES: StrategyTemplate[] = [
  // 1. 双均线策略
  {
    id: 'dual_ma_crossover',
    name: '双均线交叉策略',
    category: 'trend',
    description: '基于快慢均线交叉的趋势跟踪策略，当快线上穿慢线时买入，下穿时卖出',
    version: '1.0.0',
    author: 'QuantMind Team',
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),

    tags: ['trend', 'ma', 'crossover', 'beginner'],
    suitableMarkets: ['CN', 'US'],
    suitableTimeframes: ['1d', '1w'],
    suitableRiskLevels: ['low', 'medium'],
    minCapital: 10000,
    maxSymbols: 5,

    requiredComponents: [
      dataComponent,
      {
        type: 'LOGIC',
        name: 'DualMABacktester',
        description: '双均线回测逻辑',
        codeTemplate: '',
        requiredParams: [],
        validation: {
          requiredParams: [],
          validationRules: [],
          dependencies: []
        },
        parameters: {
          fastPeriod: 10,
          slowPeriod: 30,
          signalMethod: 'crossover'
        }
      },
      riskComponent,
      performanceComponent
    ],

    defaultParameters: {
      description: '双均线交叉策略',
      market: 'CN',
      timeframe: '1d',
      riskLevel: 'medium',
      style: 'trend',
      initialCapital: 100000,
      maxDrawdown: 15,
      commissionRate: 0.003,
      slippage: 0.001,
      strategyLength: 'medium',
      backtestPeriod: '2年',
      fastMA: 10,
      slowMA: 30
    } as Partial<any>,

    validationRules: trendValidationRules,

    codeTemplate: `# Strategy Template
# Generated by QuantMind

def initialize(context):
    pass

def handle_data(context, data):
    pass`,
    metadata: {
      complexity: 'low',
      estimatedBacktestTime: '5-10分钟',
      dependencies: ['pandas', 'talib', 'numpy'],
      performance: {
        expectedReturn: '15-25%',
        maxDrawdown: '10-20%',
        sharpeRatio: '0.8-1.2'
      }
    }
  },

  // 2. MACD策略
  {
    id: 'macd_strategy',
    name: 'MACD趋势策略',
    category: 'trend',
    description: '基于MACD指标的趋势跟踪策略，利用MACD线与信号线的交叉产生交易信号',
    version: '1.0.0',
    author: 'QuantMind Team',
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),

    tags: ['trend', 'macd', 'momentum', 'intermediate'],
    suitableMarkets: ['CN', 'US', 'HK'],
    suitableTimeframes: ['1d', '4h'],
    suitableRiskLevels: ['low', 'medium'],
    minCapital: 15000,
    maxSymbols: 8,

    requiredComponents: [
      dataComponent,
      {
        type: 'LOGIC',
        name: 'MACDBacktester',
        description: 'MACD回测逻辑',
        codeTemplate: '',
        requiredParams: [],
        validation: {
          requiredParams: [],
          validationRules: [],
          dependencies: []
        },
        parameters: {
          fastPeriod: 12,
          slowPeriod: 26,
          signalPeriod: 9,
          signalMethod: 'crossover'
        }
      },
      riskComponent,
      performanceComponent
    ],

    defaultParameters: {
      description: 'MACD趋势策略',
      market: 'CN',
      timeframe: '1d',
      riskLevel: 'medium',
      style: 'trend',
      initialCapital: 100000,
      maxDrawdown: 20,
      commissionRate: 0.003,
      slippage: 0.001,
      strategyLength: 'medium',
      backtestPeriod: '3年',
      fastPeriod: 12,
      slowPeriod: 26,
      signalPeriod: 9
    } as Partial<any>,

    validationRules: [
      ...trendValidationRules,
      {
        field: 'signalPeriod',
        rule: 'required|min:5|max:20',
        message: '信号线周期必须在5-20之间'
      }
    ],

    codeTemplate: `# Strategy Template
# Generated by QuantMind

def initialize(context):
    pass

def handle_data(context, data):
    pass`,
    metadata: {
      complexity: 'medium',
      estimatedBacktestTime: '10-15分钟',
      dependencies: ['pandas', 'talib', 'numpy', 'scipy'],
      performance: {
        expectedReturn: '20-35%',
        maxDrawdown: '15-25%',
        sharpeRatio: '1.0-1.5'
      }
    }
  },

  // 3. 布林带策略
  {
    id: 'bollinger_bands',
    name: '布林带均值回归策略',
    category: 'mean_reversion',
    description: '基于布林带的均值回归策略，价格触及上轨时卖出，触及下轨时买入',
    version: '1.0.0',
    author: 'QuantMind Team',
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),

    tags: ['mean_reversion', 'volatility', 'bollinger', 'intermediate'],
    suitableMarkets: ['CN', 'US'],
    suitableTimeframes: ['1h', '4h', '1d'],
    suitableRiskLevels: ['medium'],
    minCapital: 20000,
    maxSymbols: 6,

    requiredComponents: [
      dataComponent,
      {
        type: 'LOGIC',
        name: 'BollingerBandsBacktester',
        description: '布林带回测逻辑',
        codeTemplate: '',
        requiredParams: [],
        validation: {
          requiredParams: [],
          validationRules: [],
          dependencies: []
        },
        parameters: {
          period: 20,
          stdDev: 2,
          entryMethod: 'touch',
          exitMethod: 'middle'
        }
      },
      {
        ...riskComponent,
        parameters: {
          stopLoss: 8,
          takeProfit: 12,
          maxDrawdown: 15,
          positionSize: 15
        }
      },
      performanceComponent
    ],

    defaultParameters: {
      description: '布林带均值回归策略',
      market: 'CN',
      timeframe: '4h',
      riskLevel: 'medium',
      style: 'mean_reversion',
      initialCapital: 100000,
      maxDrawdown: 15,
      commissionRate: 0.003,
      slippage: 0.001,
      strategyLength: 'medium',
      backtestPeriod: '2年',
      period: 20,
      stdDev: 2
    } as Partial<any>,

    validationRules: [
      ...meanReversionValidationRules,
      {
        field: 'stdDev',
        rule: 'required|min:1.5|max:3',
        message: '标准差倍数必须在1.5-3之间'
      }
    ],

    codeTemplate: `# Strategy Template
# Generated by QuantMind

def initialize(context):
    pass

def handle_data(context, data):
    pass`,
    metadata: {
      complexity: 'medium',
      estimatedBacktestTime: '10-20分钟',
      dependencies: ['pandas', 'talib', 'numpy', 'scipy'],
      performance: {
        expectedReturn: '18-30%',
        maxDrawdown: '12-20%',
        sharpeRatio: '0.9-1.3'
      }
    }
  },

  // 4. RSI策略
  {
    id: 'rsi_strategy',
    name: 'RSI超买超卖策略',
    category: 'momentum',
    description: '基于RSI指标的超买超卖策略，RSI低于30时买入，高于70时卖出',
    version: '1.0.0',
    author: 'QuantMind Team',
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),

    tags: ['momentum', 'rsi', 'overbought_oversold', 'beginner'],
    suitableMarkets: ['CN', 'US', 'HK', 'GLOBAL'],
    suitableTimeframes: ['1h', '4h', '1d'],
    suitableRiskLevels: ['medium'],
    minCapital: 15000,
    maxSymbols: 10,

    requiredComponents: [
      dataComponent,
      {
        type: 'LOGIC',
        name: 'RSIBacktester',
        description: 'RSI回测逻辑',
        codeTemplate: '',
        requiredParams: [],
        validation: {
          requiredParams: [],
          validationRules: [],
          dependencies: []
        },
        parameters: {
          period: 14,
          oversoldLevel: 30,
          overboughtLevel: 70,
          confirmationMethod: 'single_candle'
        }
      },
      {
        ...riskComponent,
        parameters: {
          stopLoss: 6,
          takeProfit: 18,
          maxDrawdown: 12,
          positionSize: 12
        }
      },
      performanceComponent
    ],

    defaultParameters: {
      description: 'RSI超买超卖策略',
      market: 'CN',
      timeframe: '1d',
      riskLevel: 'medium',
      style: 'momentum',
      initialCapital: 100000,
      maxDrawdown: 12,
      commissionRate: 0.003,
      slippage: 0.001,
      strategyLength: 'short',
      backtestPeriod: '2年',
      rsiPeriod: 14,
      oversoldLevel: 30,
      overboughtLevel: 70
    } as Partial<any>,

    validationRules: [
      ...baseValidationRules,
      {
        field: 'rsiPeriod',
        rule: 'required|min:5|max:30',
        message: 'RSI周期必须在5-30之间'
      },
      {
        field: 'oversoldLevel',
        rule: 'required|min:10|max:40',
        message: '超卖水平必须在10-40之间'
      },
      {
        field: 'overboughtLevel',
        rule: 'required|min:60|max:90',
        message: '超买水平必须在60-90之间'
      }
    ],

    codeTemplate: `# Strategy Template
# Generated by QuantMind

def initialize(context):
    pass

def handle_data(context, data):
    pass`,
    metadata: {
      complexity: 'low',
      estimatedBacktestTime: '5-15分钟',
      dependencies: ['pandas', 'talib', 'numpy'],
      performance: {
        expectedReturn: '15-25%',
        maxDrawdown: '10-18%',
        sharpeRatio: '0.8-1.2'
      }
    }
  },

  // 5. 海龟交易策略
  {
    id: 'turtle_trading',
    name: '海龟交易策略',
    category: 'breakout',
    description: '经典的海龟交易策略，基于突破20日和60日高低点的趋势跟踪系统',
    version: '1.0.0',
    author: 'QuantMind Team',
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),

    tags: ['breakout', 'trend', 'position_sizing', 'advanced'],
    suitableMarkets: ['GLOBAL', 'CN', 'US'],
    suitableTimeframes: ['1d'],
    suitableRiskLevels: ['medium', 'high'],
    minCapital: 50000,
    maxSymbols: 12,

    requiredComponents: [
      dataComponent,
      {
        type: 'LOGIC',
        name: 'TurtleTradingBacktester',
        description: '海龟交易回测逻辑',
        codeTemplate: '',
        requiredParams: [],
        validation: {
          requiredParams: [],
          validationRules: [],
          dependencies: []
        },
        parameters: {
          entryPeriod: 20,
          exitPeriod: 10,
          stopLossATR: 2,
          positionSizingMethod: 'turtle',
          maxUnits: 4
        }
      },
      {
        ...riskComponent,
        parameters: {
          stopLoss: 10,
          takeProfit: 30,
          maxDrawdown: 20,
          positionSize: 25
        }
      },
      performanceComponent
    ],

    defaultParameters: {
      description: '海龟交易策略',
      market: 'CN',
      timeframe: '1d',
      riskLevel: 'high',
      style: 'trend',
      initialCapital: 200000,
      maxDrawdown: 20,
      commissionRate: 0.003,
      slippage: 0.001,
      strategyLength: 'long',
      backtestPeriod: '5年',
      entryPeriod: 20,
      exitPeriod: 10
    } as Partial<any>,

    validationRules: [
      ...baseValidationRules,
      {
        field: 'entryPeriod',
        rule: 'required|min:10|max:50',
        message: '入场周期必须在10-50之间'
      },
      {
        field: 'exitPeriod',
        rule: 'required|min:5|max:30',
        message: '出场周期必须在5-30之间'
      }
    ],

    codeTemplate: `# Strategy Template
# Generated by QuantMind

def initialize(context):
    pass

def handle_data(context, data):
    pass`,
    metadata: {
      complexity: 'high',
      estimatedBacktestTime: '20-30分钟',
      dependencies: ['pandas', 'talib', 'numpy', 'scipy', 'matplotlib'],
      performance: {
        expectedReturn: '25-40%',
        maxDrawdown: '20-30%',
        sharpeRatio: '1.2-1.8'
      }
    }
  },

  // 6. 配对交易策略
  {
    id: 'pairs_trading',
    name: '统计套利配对交易策略',
    category: 'arbitrage',
    description: '基于统计套利的配对交易策略，交易两个高度相关的金融工具',
    version: '1.0.0',
    author: 'QuantMind Team',
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),

    tags: ['arbitrage', 'pairs', 'statistical', 'advanced'],
    suitableMarkets: ['CN', 'US'],
    suitableTimeframes: ['1h', '1d'],
    suitableRiskLevels: ['low', 'medium'],
    minCapital: 30000,
    maxSymbols: 2,

    requiredComponents: [
      {
        ...dataComponent,
        parameters: {
          markets: ['CN'],
          dataSources: ['YahooFinance', 'Wind'],
          preprocessing: true,
          pairAnalysis: true
        }
      },
      {
        type: 'LOGIC',
        name: 'PairsTradingBacktester',
        description: '配对交易回测逻辑',
        codeTemplate: '',
        requiredParams: [],
        validation: {
          requiredParams: [],
          validationRules: [],
          dependencies: []
        },
        parameters: {
          lookbackPeriod: 60,
          entryThreshold: 2,
          exitThreshold: 0.5,
          hedgeRatioMethod: 'ols',
          correlationThreshold: 0.7
        }
      },
      {
        ...riskComponent,
        parameters: {
          stopLoss: 5,
          takeProfit: 10,
          maxDrawdown: 8,
          positionSize: 20
        }
      },
      performanceComponent
    ],

    defaultParameters: {
      description: '统计套利配对交易策略',
      market: 'CN',
      timeframe: '1d',
      riskLevel: 'low',
      style: 'arbitrage',
      initialCapital: 100000,
      maxDrawdown: 8,
      commissionRate: 0.003,
      slippage: 0.001,
      strategyLength: 'medium',
      backtestPeriod: '3年',
      lookbackPeriod: 60,
      entryThreshold: 2
    } as Partial<any>,

    validationRules: [
      ...meanReversionValidationRules,
      {
        field: 'correlationThreshold',
        rule: 'required|min:0.5|max:0.95',
        message: '相关系数阈值必须在0.5-0.95之间'
      }
    ],

    codeTemplate: `# Strategy Template
# Generated by QuantMind

def initialize(context):
    pass

def handle_data(context, data):
    pass`,
    metadata: {
      complexity: 'high',
      estimatedBacktestTime: '25-35分钟',
      dependencies: ['pandas', 'numpy', 'scipy', 'statsmodels', 'sklearn'],
      performance: {
        expectedReturn: '12-20%',
        maxDrawdown: '5-12%',
        sharpeRatio: '1.5-2.0'
      }
    }
  },

  // 7. 网格交易策略
  {
    id: 'grid_trading',
    name: '网格交易策略',
    category: 'mean_reversion',
    description: '在价格区间内设置买卖网格，通过反复小赚获得收益',
    version: '1.0.0',
    author: 'QuantMind Team',
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),

    tags: ['mean_reversion', 'grid', 'range_trading', 'intermediate'],
    suitableMarkets: ['CN', 'GLOBAL'],
    suitableTimeframes: ['15m', '1h', '4h'],
    suitableRiskLevels: ['medium'],
    minCapital: 25000,
    maxSymbols: 3,

    requiredComponents: [
      dataComponent,
      {
        type: 'LOGIC',
        name: 'GridTradingBacktester',
        description: '网格交易回测逻辑',
        codeTemplate: '',
        requiredParams: [],
        validation: {
          requiredParams: [],
          validationRules: [],
          dependencies: []
        },
        parameters: {
          gridCount: 10,
          gridRange: 0.2,
          basePrice: 'sma_20',
          gridMethod: 'arithmatic',
          profitTarget: 0.02
        }
      },
      {
        ...riskComponent,
        parameters: {
          stopLoss: 15,
          takeProfit: 5,
          maxDrawdown: 25,
          positionSize: 30
        }
      },
      performanceComponent
    ],

    defaultParameters: {
      description: '网格交易策略',
      market: 'CN',
      timeframe: '1h',
      riskLevel: 'medium',
      style: 'mean_reversion',
      initialCapital: 100000,
      maxDrawdown: 25,
      commissionRate: 0.003,
      slippage: 0.001,
      strategyLength: 'short',
      backtestPeriod: '1年',
      gridCount: 10,
      gridRange: 0.2
    } as Partial<any>,

    validationRules: [
      ...baseValidationRules,
      {
        field: 'gridCount',
        rule: 'required|min:5|max:20',
        message: '网格数量必须在5-20之间'
      },
      {
        field: 'gridRange',
        rule: 'required|min:0.1|max:0.5',
        message: '网格范围必须在0.1-0.5之间'
      }
    ],

    codeTemplate: `# Strategy Template
# Generated by QuantMind

def initialize(context):
    pass

def handle_data(context, data):
    pass`,
    metadata: {
      complexity: 'medium',
      estimatedBacktestTime: '15-25分钟',
      dependencies: ['pandas', 'numpy', 'talib'],
      performance: {
        expectedReturn: '20-35%',
        maxDrawdown: '15-25%',
        sharpeRatio: '0.7-1.0'
      }
    }
  },

  // 8. 动量策略
  {
    id: 'momentum_strategy',
    name: '价格动量策略',
    category: 'momentum',
    description: '基于价格动量的策略，买入表现强势的股票，卖出表现弱势的股票',
    version: '1.0.0',
    author: 'QuantMind Team',
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),

    tags: ['momentum', 'relative_strength', 'trend', 'intermediate'],
    suitableMarkets: ['CN', 'US'],
    suitableTimeframes: ['1d', '1w'],
    suitableRiskLevels: ['medium', 'high'],
    minCapital: 30000,
    maxSymbols: 10,

    requiredComponents: [
      dataComponent,
      {
        type: 'LOGIC',
        name: 'MomentumBacktester',
        description: '动量策略回测逻辑',
        codeTemplate: '',
        requiredParams: [],
        validation: {
          requiredParams: [],
          validationRules: [],
          dependencies: []
        },
        required: true,
        parameters: {
          lookbackPeriod: 90,
          formationPeriod: 60,
          holdingPeriod: 30,
          rankingMethod: 'total_return',
          topN: 3
        }
      },
      {
        ...riskComponent,
        parameters: {
          stopLoss: 8,
          takeProfit: 25,
          maxDrawdown: 18,
          positionSize: 20
        }
      },
      performanceComponent
    ],

    defaultParameters: {
      description: '价格动量策略',
      market: 'CN',
      timeframe: '1d',
      riskLevel: 'medium',
      style: 'momentum',
      initialCapital: 100000,
      maxDrawdown: 18,
      commissionRate: 0.003,
      slippage: 0.001,
      strategyLength: 'medium',
      backtestPeriod: '3年',
      lookbackPeriod: 90,
      formationPeriod: 60,
      holdingPeriod: 30
    } as Partial<any>,

    validationRules: [
      ...baseValidationRules,
      {
        field: 'lookbackPeriod',
        rule: 'required|min:30|max:252',
        message: '回看周期必须在30-252之间'
      },
      {
        field: 'holdingPeriod',
        rule: 'required|min:5|max:90',
        message: '持有周期必须在5-90之间'
      }
    ],

    codeTemplate: `# Strategy Template
# Generated by QuantMind

def initialize(context):
    pass

def handle_data(context, data):
    pass`,
    metadata: {
      complexity: 'medium',
      estimatedBacktestTime: '20-30分钟',
      dependencies: ['pandas', 'numpy', 'scipy'],
      performance: {
        expectedReturn: '22-35%',
        maxDrawdown: '15-25%',
        sharpeRatio: '1.0-1.4'
      }
    }
  },

  // 9. 多因子选股策略
  {
    id: 'multi_factor',
    name: '多因子选股策略',
    category: 'trend',
    description: '结合价值、成长、质量、动量等多个因子进行股票选择的策略',
    version: '1.0.0',
    author: 'QuantMind Team',
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),

    tags: ['multi_factor', 'stock_selection', 'quantitative', 'advanced'],
    suitableMarkets: ['CN'],
    suitableTimeframes: ['1d', '1w'],
    suitableRiskLevels: ['low', 'medium'],
    minCapital: 50000,
    maxSymbols: 20,

    requiredComponents: [
      {
        ...dataComponent,
        parameters: {
          markets: ['CN'],
          dataSources: ['Wind', 'JoinQuant', 'YahooFinance'],
          preprocessing: true,
          fundamentalData: true
        }
      },
      {
        type: 'LOGIC',
        name: 'MultiFactorBacktester',
        description: '多因子回测逻辑',
        codeTemplate: '',
        requiredParams: [],
        validation: {
          requiredParams: [],
          validationRules: [],
          dependencies: []
        },
        required: true,
        parameters: {
          factors: ['value', 'growth', 'quality', 'momentum'],
          factorWeights: [0.25, 0.25, 0.25, 0.25],
          rankingMethod: 'weighted_score',
          rebalanceFrequency: 'monthly',
          topN: 10
        }
      },
      {
        ...riskComponent,
        parameters: {
          stopLoss: 12,
          takeProfit: 30,
          maxDrawdown: 15,
          positionSize: 10
        }
      },
      performanceComponent
    ],

    defaultParameters: {
      description: '多因子选股策略',
      market: 'CN',
      timeframe: '1d',
      riskLevel: 'low',
      style: 'trend',
      initialCapital: 200000,
      maxDrawdown: 15,
      commissionRate: 0.003,
      slippage: 0.001,
      strategyLength: 'long',
      backtestPeriod: '5年',
      rebalanceFrequency: 'monthly',
      topN: 10
    } as Partial<any>,

    validationRules: [
      ...baseValidationRules,
      {
        field: 'topN',
        rule: 'required|min:5|max:30',
        message: '选股数量必须在5-30之间'
      }
    ],

    codeTemplate: `# Strategy Template
# Generated by QuantMind

def initialize(context):
    pass

def handle_data(context, data):
    pass`,
    metadata: {
      complexity: 'high',
      estimatedBacktestTime: '30-45分钟',
      dependencies: ['pandas', 'numpy', 'scipy', 'statsmodels', 'sklearn'],
      performance: {
        expectedReturn: '20-30%',
        maxDrawdown: '12-20%',
        sharpeRatio: '1.2-1.6'
      }
    }
  },

  // 10. 波动率突破策略
  {
    id: 'volatility_breakout',
    name: '波动率突破策略',
    category: 'breakout',
    description: '基于波动率的突破策略，在低波动率后的突破时进行交易',
    version: '1.0.0',
    author: 'QuantMind Team',
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),

    tags: ['breakout', 'volatility', 'atr', 'intermediate'],
    suitableMarkets: ['CN', 'US', 'GLOBAL'],
    suitableTimeframes: ['1h', '4h', '1d'],
    suitableRiskLevels: ['medium'],
    minCapital: 25000,
    maxSymbols: 6,

    requiredComponents: [
      dataComponent,
      {
        type: 'LOGIC',
        name: 'VolatilityBreakoutBacktester',
        description: '波动率突破回测逻辑',
        codeTemplate: '',
        requiredParams: [],
        validation: {
          requiredParams: [],
          validationRules: [],
          dependencies: []
        },
        required: true,
        parameters: {
          atrPeriod: 14,
          breakoutMultiplier: 2,
          volatilityLookback: 20,
          entryMethod: 'percentage',
          exitMethod: 'trailing_stop'
        }
      },
      {
        ...riskComponent,
        parameters: {
          stopLoss: 8,
          takeProfit: 20,
          maxDrawdown: 15,
          positionSize: 15
        }
      },
      performanceComponent
    ],

    defaultParameters: {
      description: '波动率突破策略',
      market: 'CN',
      timeframe: '4h',
      riskLevel: 'medium',
      style: 'trend',
      initialCapital: 100000,
      maxDrawdown: 15,
      commissionRate: 0.003,
      slippage: 0.001,
      strategyLength: 'medium',
      backtestPeriod: '2年',
      atrPeriod: 14,
      breakoutMultiplier: 2
    } as Partial<any>,

    validationRules: [
      ...baseValidationRules,
      {
        field: 'atrPeriod',
        rule: 'required|min:5|max:30',
        message: 'ATR周期必须在5-30之间'
      },
      {
        field: 'breakoutMultiplier',
        rule: 'required|min:1|max:5',
        message: '突破倍数必须在1-5之间'
      }
    ],

    codeTemplate: `# Strategy Template
# Generated by QuantMind

def initialize(context):
    pass

def handle_data(context, data):
    pass`,
    metadata: {
      complexity: 'medium',
      estimatedBacktestTime: '15-25分钟',
      dependencies: ['pandas', 'talib', 'numpy', 'scipy'],
      performance: {
        expectedReturn: '18-30%',
        maxDrawdown: '12-20%',
        sharpeRatio: '0.9-1.3'
      }
    }
  },

  // 11. 均值回归组合策略
  {
    id: 'mean_reversion_portfolio',
    name: '均值回归组合策略',
    category: 'mean_reversion',
    description: '基于多个股票的均值回归特性构建投资组合的策略',
    version: '1.0.0',
    author: 'QuantMind Team',
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),

    tags: ['mean_reversion', 'portfolio', 'statistical', 'advanced'],
    suitableMarkets: ['CN', 'US'],
    suitableTimeframes: ['1d'],
    suitableRiskLevels: ['low', 'medium'],
    minCapital: 40000,
    maxSymbols: 15,

    requiredComponents: [
      dataComponent,
      {
        type: 'LOGIC',
        name: 'MeanReversionPortfolioBacktester',
        description: '均值回归组合回测逻辑',
        codeTemplate: '',
        requiredParams: [],
        validation: {
          requiredParams: [],
          validationRules: [],
          dependencies: []
        },
        required: true,
        parameters: {
          lookbackPeriod: 252,
          zscoreThreshold: 2,
          rebalanceFrequency: 'weekly',
          positionSizing: 'equal_weight',
          maxPositions: 10
        }
      },
      {
        ...riskComponent,
        parameters: {
          stopLoss: 6,
          takeProfit: 15,
          maxDrawdown: 12,
          positionSize: 8
        }
      },
      performanceComponent
    ],

    defaultParameters: {
      description: '均值回归组合策略',
      market: 'CN',
      timeframe: '1d',
      riskLevel: 'low',
      style: 'mean_reversion',
      initialCapital: 150000,
      maxDrawdown: 12,
      commissionRate: 0.003,
      slippage: 0.001,
      strategyLength: 'long',
      backtestPeriod: '4年',
      lookbackPeriod: 252,
      zscoreThreshold: 2
    } as Partial<any>,

    validationRules: [
      ...meanReversionValidationRules,
      {
        field: 'zscoreThreshold',
        rule: 'required|min:1|max:3',
        message: 'Z-score阈值必须在1-3之间'
      }
    ],

    codeTemplate: `# Strategy Template
# Generated by QuantMind

def initialize(context):
    pass

def handle_data(context, data):
    pass`,
    metadata: {
      complexity: 'high',
      estimatedBacktestTime: '25-40分钟',
      dependencies: ['pandas', 'numpy', 'scipy', 'statsmodels', 'sklearn'],
      performance: {
        expectedReturn: '15-25%',
        maxDrawdown: '8-15%',
        sharpeRatio: '1.3-1.8'
      }
    }
  },

  // 8. 激进版TopK策略
  {
    id: 'aggressive_topk_strategy',
    name: '激进版截面TopK策略',
    category: 'momentum',
    description: '基于机器学习预测分数的激进版TopK动量轮动策略，零容忍度每日极致换仓，捕捉高频势能',
    version: '1.0.0',
    author: 'QuantMind Team',
    createdAt: new Date('2026-02-23'),
    updatedAt: new Date('2026-02-23'),

    tags: ['momentum', 'machine_learning', 'high_frequency', 'aggressive'],
    suitableMarkets: ['CN'],
    suitableTimeframes: ['1d'],
    suitableRiskLevels: ['high'],
    minCapital: 1000000,
    maxSymbols: 50,

    requiredComponents: [
      {
        type: 'DATA_HANDLING',
        name: 'QlibDataProcessor',
        description: 'Qlib高级数据处理器',
        codeTemplate: '',
        requiredParams: [],
        validation: { requiredParams: [], validationRules: [], dependencies: [] },
        parameters: { markets: ['CN'], dataSources: ['Qlib'] }
      },
      {
        type: 'LOGIC',
        name: 'TopkDropoutStrategy',
        description: 'TopK丢弃轮动逻辑',
        codeTemplate: '',
        requiredParams: [],
        validation: { requiredParams: [], validationRules: [], dependencies: [] },
        parameters: { topk: 50, n_drop: 10 }
      },
      {
        type: 'RISK_CONTROL',
        name: 'WeightStrategyManager',
        description: '等权全仓风控管理器',
        codeTemplate: '',
        requiredParams: [],
        validation: { requiredParams: [], validationRules: [], dependencies: [] },
        parameters: { risk_degree: 0.95 }
      }
    ],

    defaultParameters: {
      description: '激进版截面TopK策略',
      market: 'CN',
      timeframe: '1d',
      riskLevel: 'high',
      style: 'momentum',
      initialCapital: 1000000,
      maxDrawdown: 35,
      commissionRate: 0.0015,
      slippage: 0,
      strategyLength: 'short',
      backtestPeriod: '1年',
      topk: 50,
      n_drop: 10
    } as Partial<any>,

    validationRules: [
      ...baseValidationRules,
      {
        field: 'topk',
        rule: 'required|min:10|max:100',
        message: '持仓数量限制必须在10-100之间'
      },
      {
        field: 'n_drop',
        rule: 'required|min:1|max:20',
        message: '缓冲换仓数量必须在1-20之间（默认按 topk 的20%）'
      }
    ],

    codeTemplate: `# Strategy Template
# Generated by QuantMind

def initialize(context):
    pass

def handle_data(context, data):
    pass`,
    metadata: {
      complexity: 'high',
      estimatedBacktestTime: '1-3分钟',
      dependencies: ['qlib', 'pandas', 'numpy', 'lightgbm'],
      performance: {
        expectedReturn: '70-160%',
        maxDrawdown: '30-40%',
        sharpeRatio: '2.0-3.5'
      }
    }
  }
];

// ==================== 模板分类导出 ====================
// (函数定义移至文件底部，使用 ALL_TEMPLATES)

// ==================== 模板统计信息 ====================

// 注意：MiniQMT支持已移除，仅保留标准策略模板
const ALL_TEMPLATES = [...STRATEGY_TEMPLATES];

// ==================== 更新的导出函数 ====================

export const getTemplatesByCategory = (category: StrategyCategory): StrategyTemplate[] => {
  return ALL_TEMPLATES.filter(template => template.category === category);
};

export const getTemplatesByRiskLevel = (riskLevel: RiskLevel): StrategyTemplate[] => {
  return ALL_TEMPLATES.filter(template =>
    template.suitableRiskLevels.includes(riskLevel)
  );
};

export const getTemplatesByMarket = (market: MarketType): StrategyTemplate[] => {
  return ALL_TEMPLATES.filter(template =>
    template.suitableMarkets.includes(market)
  );
};

export const getTemplatesByComplexity = (complexity: 'low' | 'medium' | 'high'): StrategyTemplate[] => {
  return ALL_TEMPLATES.filter(template =>
    template.metadata.complexity === complexity
  );
};

export const getTemplateById = (id: string): StrategyTemplate | undefined => {
  return ALL_TEMPLATES.find(template => template.id === id);
};

export const getAllTemplates = (): StrategyTemplate[] => {
  return ALL_TEMPLATES;
};

// MiniQMT支持已移除
export const getMiniQMTTemplates = (): StrategyTemplate[] => {
  console.warn('MiniQMT support has been removed. Returning empty array.');
  return [];
};

export const isMiniQMTTemplate = (template: StrategyTemplate): boolean => {
  return false;
};

export const getTemplateByFramework = (framework: 'standard' | 'miniqmt'): StrategyTemplate[] => {
  if (framework === 'miniqmt') {
    console.warn('MiniQMT support has been removed. Returning standard templates.');
    return STRATEGY_TEMPLATES;
  }
  return STRATEGY_TEMPLATES;
};

// ==================== 更新的模板统计信息 ====================

export const TEMPLATE_STATS = {
  total: ALL_TEMPLATES.length,
  standard: STRATEGY_TEMPLATES.length,
  byCategory: {
    'trend': ALL_TEMPLATES.filter(t => t.category === 'trend').length,
    'mean_reversion': ALL_TEMPLATES.filter(t => t.category === 'mean_reversion').length,
    'momentum': ALL_TEMPLATES.filter(t => t.category === 'momentum').length,
    'breakout': ALL_TEMPLATES.filter(t => t.category === 'breakout').length,
    'arbitrage': ALL_TEMPLATES.filter(t => t.category === 'arbitrage').length,
    'custom': ALL_TEMPLATES.filter(t => t.category === 'custom').length
  },
  byComplexity: {
    low: ALL_TEMPLATES.filter(t => t.metadata.complexity === 'low').length,
    medium: ALL_TEMPLATES.filter(t => t.metadata.complexity === 'medium').length,
    high: ALL_TEMPLATES.filter(t => t.metadata.complexity === 'high').length
  },
  avgMinCapital: Math.round(
    ALL_TEMPLATES.reduce((sum, t) => sum + t.minCapital, 0) / ALL_TEMPLATES.length
  ),
  avgComplexity:
    ALL_TEMPLATES.reduce((sum, t) => {
      const complexityScore = t.metadata.complexity === 'low' ? 1 :
        t.metadata.complexity === 'medium' ? 2 : 3;
      return sum + complexityScore;
    }, 0) / ALL_TEMPLATES.length
};
